name: s3-depl-dev
on:
    push:
        branches:
            - main
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checking out code
              uses: actions/checkout@v3
            - name: Installing Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "16"
            - name: Creating build directory
              run: |
                  mkdir build && cd build
            - name: Building project
              run: npm install && npm run build
              env:
                  NEXT_PUBLIC_API_URL: ""
            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v1
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: us-west-1
            - name: Deploy to S3 bucket
              run: aws s3 sync . s3://dev-pizzApp-deploy --delete
